.\"
.\" Copyright 2020, 2026 Colin Percival
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd August 29, 2026
.Dt EBSNVME 8
.Os
.Sh NAME
.Nm ebsnvme , ebsnvme-id , ebsnvme-stats
.Nd NVMe disk information tool for Amazon EC2
.Sh SYNOPSIS
.Nm ebsnvme-id
.Op Fl b
.Op Fl m
.Op Fl s
.Op Fl u
.Op Fl v
.Ar device
.Nm ebsnvme-stats
.Op Fl i Ar interval
.Op Fl j
.Ar device
.Sh DESCRIPTION
The Amazon EC2
.Dq Nitro
platform exposes disks to virtual machines via the NVM Express protocol.
There are two types of disks so exposed: Elastic Block Store disks, which
persist and can be detached and reattached to different virtual machines,
and Instance Store disks (also known as
.Dq Ephemeral
disks), which exist only while the virtual machine is running.
.Pp
Amazon Linux provides a tool
.Dq ebsnvme
for identifying and retrieving performance statistics on the attached Elastic
Block Store disks; this
.Nm
is a re-implementation which also exposes some information about Instance
Store disks.
.Pp
This tool can be invoked as
.Nm ebsnvme Cm id
which is equivalent to
.Nm ebsnvme-id ,
or as
.Nm ebsnvme Cm stats
which is equivalent to
.Nm ebsnvme-stats .
.Pp
The options to
.Nm ebsnvme-id
are as follows:
.Bl -tag -width indent
.It Fl b
Print the
.Dq Linux device name
associated with the specified Elastic Block Store disk.
.It Fl m
Print the Model Number of the disk; this is either
.Dq Amazon Elastic Block Store
or
.Dq Amazon EC2 NVMe Instance Storage
depending on the type of disk.
.It Fl s
Print the Serial Number of the disk.
.It Fl u
Identical to the
.Fl b
option.
.It Fl v
Print
.Dq Volume ID:
followed by the volume ID of the Elastic Block Store disk.
.El
.Pp
If no options are specified,
.Nm ebsnvme-id
operates as if invoked with the options
.Fl v
.Fl b .
.Pp
If multiple options are specified, output is printed for each
option, in the order
.Fl v
.Op Fl b | Fl u
.Fl m
.Fl s .
.Pp
The options to
.Nm ebsnvme-stats
are as follows:
.Bl -tag -width indent
.It Fl i Ar interval
After the initial statistics, print further statistics every
.Ar interval
seconds showing the delta since the previously printed statistics.
.It Fl j
Print statistics in JSON format.
.El
.Sh SEE ALSO
.Xr nvmecontrol 8
.Sh AUTHORS
.Nm
was written by
.An Colin Percival Aq Mt cperciva@FreeBSD.org
based on the
.Dq ebsnvme-id
tool published by Amazon.com, Inc.
